- name: Restart sshd service
  ansible.builtin.systemd:
    name: ssh
    state: restarted

- name: Restart ssh socket
  ansible.builtin.systemd_service:
    state: restarted
    daemon_reload: true
    name: ssh.socket